"""🆕 Add FedExAPIResponse table

Revision ID: 238636cc64b6
Revises: e49fca6feeac
Create Date: 2025-04-06 07:13:08.228047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238636cc64b6'
down_revision: Union[str, None] = 'e49fca6feeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fedex_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('packaging_type', sa.String(), nullable=True),
    sa.Column('commit_day_of_week', sa.String(), nullable=True),
    sa.Column('commit_date', sa.Date(), nullable=True),
    sa.Column('transit_time', sa.String(), nullable=True),
    sa.Column('saturday_delivery', sa.Boolean(), nullable=True),
    sa.Column('service_code', sa.String(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['tnt_input_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fedex_response_input_id', 'fedex_response', ['input_id'], unique=False)
    op.create_index(op.f('ix_fedex_response_id'), 'fedex_response', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fedex_response_id'), table_name='fedex_response')
    op.drop_index('idx_fedex_response_input_id', table_name='fedex_response')
    op.drop_table('fedex_response')
    # ### end Alembic commands ###
