"""Update BatchSettings fields

Revision ID: 8a84c9908ae4
Revises: ca37695e879b
Create Date: 2025-03-28 21:35:59.507785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a84c9908ae4'
down_revision: Union[str, None] = 'ca37695e879b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_settings', sa.Column('avv_flag', sa.Boolean(), nullable=True))
    op.add_column('batch_settings', sa.Column('residential_indicator', sa.String(), nullable=True))
    op.drop_index('ix_batch_settings_id', table_name='batch_settings')
    op.create_unique_constraint(None, 'batch_settings', ['batch_id'])
    op.drop_column('batch_settings', 'documents_only')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_settings', sa.Column('documents_only', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'batch_settings', type_='unique')
    op.create_index('ix_batch_settings_id', 'batch_settings', ['id'], unique=False)
    op.drop_column('batch_settings', 'residential_indicator')
    op.drop_column('batch_settings', 'avv_flag')
    # ### end Alembic commands ###
