"""Add input settings columns to TNTInputData

Revision ID: e49fca6feeac
Revises: 8a84c9908ae4
Create Date: 2025-03-28 22:48:57.890668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49fca6feeac'
down_revision: Union[str, None] = '8a84c9908ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tnt_input_data', sa.Column('ship_date', sa.Date(), nullable=True))
    op.add_column('tnt_input_data', sa.Column('avv_flag', sa.Boolean(), nullable=True))
    op.add_column('tnt_input_data', sa.Column('residential_indicator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tnt_input_data', 'residential_indicator')
    op.drop_column('tnt_input_data', 'avv_flag')
    op.drop_column('tnt_input_data', 'ship_date')
    # ### end Alembic commands ###
